-- =============================================================================
-- Raia G1.0 — Database Schema Extension
-- Adds tables for predictions, scores, interventions, and question analytics.
-- =============================================================================

-- Stores classified and analyzed questions for analytics and model improvement.
create table if not exists raia_question_log (
  id uuid primary key default gen_random_uuid(),
  user_email text,
  question text not null,
  question_type text not null,
  jurisdiction jsonb,
  time_sensitivity text not null,
  safety_flags text[] default '{}',
  safety_action text,
  confidence_level text,
  confidence_score numeric(4,2),
  sources_needed text[] default '{}',
  response_summary text,
  created_at timestamptz default now()
);

-- Stores predictions generated by Raia for analytics and auditing.
create table if not exists raia_predictions (
  id uuid primary key default gen_random_uuid(),
  prediction_class text not null,
  jurisdiction jsonb not null,
  time_horizon text,
  likelihood numeric(4,3),
  confidence_level text not null,
  confidence_score numeric(4,2),
  pattern text not null,
  drivers text[] default '{}',
  uncertainty text,
  recommended_actions text[] default '{}',
  context text,
  created_at timestamptz default now()
);

-- Stores computed scores for users and jurisdictions.
create table if not exists raia_scores (
  id uuid primary key default gen_random_uuid(),
  score_type text not null,
  subject_type text not null, -- 'user', 'jurisdiction', 'ballot', 'community'
  subject_id text not null,   -- user email, jurisdiction key, ballot id, etc.
  value integer not null,
  label text not null,
  components jsonb not null,
  explanation text,
  jurisdiction jsonb,
  computed_at timestamptz default now()
);

-- Stores triggered interventions for effectiveness tracking.
create table if not exists raia_interventions (
  id uuid primary key default gen_random_uuid(),
  intervention_type text not null,
  priority text not null,
  trigger_condition text not null,
  target_user_email text,
  jurisdiction jsonb,
  ui_module text not null,
  shown_at timestamptz default now(),
  clicked_at timestamptz,
  completed_at timestamptz,
  dismissed_at timestamptz
);

-- Indexes for common query patterns
create index if not exists idx_raia_question_log_type on raia_question_log(question_type);
create index if not exists idx_raia_question_log_created on raia_question_log(created_at);
create index if not exists idx_raia_predictions_class on raia_predictions(prediction_class);
create index if not exists idx_raia_predictions_created on raia_predictions(created_at);
create index if not exists idx_raia_scores_type_subject on raia_scores(score_type, subject_type, subject_id);
create index if not exists idx_raia_interventions_type on raia_interventions(intervention_type);
create index if not exists idx_raia_interventions_user on raia_interventions(target_user_email);
